baseURL = "https://xiarong715.github.io"
languageCode = "en-us"	## "en-us" zh-CN
title = "风笑天的博客"
theme = "maupassant-hugo"

[author]
  name = "风笑天"

[params]
  author = "风笑天"
  subtitle = "专注于Go语言(golang)、大数据、软件架构。健康。"
  keywords = "golang,go语言,go语言笔记,风笑天,大数据、软件架构"
  description = "专注于IT互联网，包括但不限于Go语言(golang)、大数据、软件架构"
  localSearch = true

  # 全局开关，开启每篇文章目录大纲
  # toc = true  


## 友情链接，可以有多个
[[params.links]]
  title = "风笑天的博客"
  name = "风笑天的博客"
  url = "https://xiarong715.github.io"

[[params.links]]
  title = "hugo"
  name = "hugo中文文档"
  url = "https://www.gohugo.org"

[[params.links]]
  title = "hugo"
  name = "hugo官网"
  url = "https://www.gohugo.io"

 ## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weght = 4